### ISSUE TITLE
No build for @kyma-project/dc-async-api-render-engine v0.3.5

### ISSUE THREAD

**Issue by alextargov** [kyma-incubator/documentation-component#107]
**Description**

In kyma-incubator we use the **@kyma-project/dc-async-api-render-engine** lib. There was a vulnerability fix in our UI which bumps the @kyma-project/dc-async-api-render-engine to v0.3.5. But it seems like there are no output files in that build. When installing this version in our repo I see only the **package.json** and the **README** within the node modules.
![image](https://user-images.githubusercontent.com/17293744/149979230-6ff90279-4acc-4797-b470-6aae97acda7c.png)

**Expected result**

Have a good build with output js files.

**Actual result**

No minified file when the package is installed.

**Steps to reproduce**

**Troubleshooting**

**Comment by desislavaa** [comment]
Fixed with latest release
