### ISSUE TITLE
All render engines in documentation component should have consistent default styling

### ISSUE THREAD

**Issue by derberg** [kyma-incubator/documentation-component#33]
**Description**

- have fiori 3 as default for all, even open api
- have instruction how to replace default styles
- release under 0.3

**Reasons**

usability of the component out of the box

**Comment by aerfio** [comment]
Note: after https://github.com/kyma-project/console/issues/684 is done please update https://github.com/kyma-incubator/documentation-component/blob/master/packages/async-api-render-engine/README.md
