### ISSUE TITLE
Provide examples in JavaScript

### ISSUE THREAD

**Issue by derberg** [kyma-incubator/documentation-component#45]
**Description**

- have examples with both, JS and TS like we have here https://github.com/kyma-project/kyma/blob/master/docs/kyma/04-04-cluster-installation.md#prerequisites (raw https://raw.githubusercontent.com/kyma-project/kyma/master/docs/kyma/04-04-cluster-installation.md)
- JS is always first on the list

**Reasons**

At the moment all examples for the component are in TypeScript, except of sandbox projects.
Believe it or not, but there is still a great number of javascript developers that do not need TypeScript at all to write good quality code :D https://insights.stackoverflow.com/survey/2019#technology-_-programming-scripting-and-markup-languages

**Comment by kwiatekus** [comment]
Not a priority
