### ISSUE TITLE
Make core independent from any JS lib/framework

### ISSUE THREAD

**Issue by magicmatatjahu** [kyma-incubator/documentation-component#50]
**Description**

At the moment we have strongly coexisting with React ecosystem in our core. For easier integration in other frameworks (Angular and Vue ecosystem, and maybe also in SvelteJS) we must extract whole React from core and make it independent from any JS lib/framework.

**Reasons**

For easier integration in other JS frameworks/libs.

**Comment by michal-hudy** [comment]
The documentation component doesn't have any adoptions rather than Kyma, so this is not a priority.
